# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "imagut"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ippei94da"]
  s.date = "2012-06-13"
  s.description = "Library to deal image files. This includes file renamer with NIKON NEF file, downloader for images on a web page."
  s.email = "ippei94da@gmail.com"
  s.executables = ["getimage", "importnef", "resizeimage"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/getimage",
    "bin/importnef",
    "bin/resizeimage",
    "lib/imagut.rb",
    "lib/imagut/nefparser.rb",
    "lib/imagut/urllogger.rb",
    "test/001.nef",
    "test/helper.rb",
    "test/test_nefparser.rb",
    "test/test_urllogger.rb",
    "test/urllogger/20120523.log",
    "test/urllogger/20120524.log"
  ]
  s.homepage = "http://github.com/ippei94da/imagut"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "IMAGe UTilities. File renamer, downloader, etc."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.5.4"])
      s.add_development_dependency(%q<filerenamer>, [">= 0.0.0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.5.4"])
      s.add_dependency(%q<filerenamer>, [">= 0.0.0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.5.4"])
    s.add_dependency(%q<filerenamer>, [">= 0.0.0"])
  end
end

